_target_: src.models.m_invariant_da.InvariantDAModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

loss:
  _target_: src.losses.MMDLoss

lambd: 1.0

f:
  _target_: src.models.components.lenet.FeatureExtractor

g:
  _target_: src.models.components.lenet.Classifier

# compile model for faster training with pytorch 2.0
compile: false
