# @package _global_

# runs with execution time profiling

defaults:
  - default

trainer:
  max_epochs: 1
  #profiler: "simple"
  #profiler: "advanced"
  #profiler: "pytorch"

  profiler:
    _target_: lightning.pytorch.profilers.PyTorchProfiler
    filename: "torch_profiler"
  fast_dev_run: true